/**
 * Enum of known environment variables
 */
export enum EnvVars {
  // general settings
  ENV = 'ENV',
  IS_E2E = 'IS_E2E',

  // logger settings
  LOG_LEVEL = 'LOG_LEVEL',
  USE_WINSTON_LOGGER = 'USE_WINSTON_LOGGER',
  LOG_DIR = 'LOG_DIR',
  CLOUDWATCH_LOGS_ENABLED = 'CLOUDWATCH_LOGS_ENABLED',

  // server settings
  PORT = 'PORT',
  QSS_HOSTNAME = 'QSS_HOSTNAME',
  LISTEN_HOSTNAME = 'LISTEN_HOSTNAME',

  // aws settings
  AWS_REGION = 'AWS_REGION',
  AWS_ACCOUNT_ID = 'AWS_ACCOUNT_ID',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_KEY = 'AWS_SECRET_KEY',
  AWS_CLIENT_LOCAL_ENDPOINT = 'AWS_CLIENT_LOCAL_ENDPOINT',

  // postgres settings
  POSTGRES_SOURCE = 'POSTGRES_SOURCE',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_DB_NAME = 'POSTGRES_DB_NAME',
  POSTGRES_USERNAME = 'POSTGRES_USERNAME',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DEBUG = 'POSTGRES_DEBUG',
  POSTGRES_READ_REPLICA_HOSTS = 'POSTGRES_READ_REPLICA_HOSTS',
  //// mikro orm-specific settings
  MIKRO_ORM_HOST = 'MIKRO_ORM_HOST',
  MIKRO_ORM_PORT = 'MIKRO_ORM_PORT',
  MIKRO_ORM_USER = 'MIKRO_ORM_USER',
  MIKRO_ORM_PASSWORD = 'MIKRO_ORM_PASSWORD',
  MIKRO_ORM_DB_NAME = 'MIKRO_ORM_DB_NAME',
  MIKRO_ORM_DEBUG = 'MIKRO_ORM_DEBUG',
  MIKRO_ORM_PREFER_TS = 'MIKRO_ORM_PREFER_TS',

  // redis settings
  REDIS_ENDPOINT = 'REDIS_ENDPOINT',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_ENABLED = 'REDIS_ENABLED',

  // hcaptcha settings
  HCAPTCHA_SECRET = 'HCAPTCHA_SECRET',
  ALLOW_HCAPTCHA_BYPASS = 'ALLOW_HCAPTCHA_BYPASS',
}
