export enum EnvVars {
  // general settings
  ENV = 'ENV',

  // logger settings
  LOG_LEVELS = 'LOG_LEVELS',

  // server settings
  PORT = 'PORT',
  HOSTNAME = 'HOSTNAME',

  // aws settings
  AWS_REGION = 'AWS_REGION',
  AWS_ACCOUNT_ID = 'AWS_ACCOUNT_ID',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_KEY = 'AWS_SECRET_KEY',

  // postgres settings
  POSTGRES_SOURCE = 'POSTGRES_SOURCE',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_DB_NAME = 'POSTGRES_DB_NAME',
  POSTGRES_USERNAME = 'POSTGRES_USERNAME',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DEBUG = 'POSTGRES_DEBUG',
  POSTGRES_READ_REPLICA_HOSTS = 'POSTGRES_READ_REPLICA_HOSTS',
  //// mikro orm-specific settings
  MIKRO_ORM_HOST = 'MIKRO_ORM_HOST',
  MIKRO_ORM_PORT = 'MIKRO_ORM_PORT',
  MIKRO_ORM_USER = 'MIKRO_ORM_USER',
  MIKRO_ORM_PASSWORD = 'MIKRO_ORM_PASSWORD',
  MIKRO_ORM_DB_NAME = 'MIKRO_ORM_DB_NAME',
  MIKRO_ORM_DEBUG = 'MIKRO_ORM_DEBUG',
  MIKRO_ORM_PREFER_TS = 'MIKRO_ORM_PREFER_TS',
}
