name: AWS Deploy

inputs:
  code_deploy_group:
    description: 'AWS CodeDeploy group name'
    required: true
  code_deploy_application:
    description: 'AWS CodeDeploy application name'
    required: true
  aws_region:
    description: 'AWS region containing EC2 instance(s)'
    required: true

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws_region }}
    - name: Deploy QSS to AWS
      shell: bash
      run: |
        commit_id=`git rev-parse HEAD`
        aws deploy create-deployment \
        --application-name ${{ inputs.code_deploy_application }} \
        --deployment-group-name ${{ inputs.code_deploy_group }} \
        --github-location repository=TryQuiet/quiet-storage-service,commitId=$commit_id \
        --ignore-application-stop-failures
        --color on