name: Setup environment

runs:
  using: composite
  steps:
    - name: Install Node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
        
    - name: Install pnpm
      uses: pnpm/action-setup@v4 # pulls version from package.json -> "packageManager"

    - name: Bootstrap app
      shell: bash
      run: |
        pnpm run bootstrap
