name: 'Setup environment'

runs:
  using: "composite"
  steps:
    - name: Install Node 22
      shell: bash
      run: |
        # install node 22
        curl -sL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh
        sudo -E bash nodesource_setup.sh
        sudo apt-get install -y nodejs
    
    - name: Install pnpm
      shell: bash
      run: |
        # install pnpm 9
        curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=9.6.0 sh -

    - name: "Install dependencies"
      shell: bash
      run: |
        pnpm i

    - name: "Build app"
      shell: bash
      run: |
        pnpm run build
