name: Setup environment

inputs:
  install-docker:
    description: 'Install and setup docker/docker compose'
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Install Node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22.14.0

    - name: Set up Docker
      uses: docker/setup-docker-action@v4
      if: ${{ inputs.install-docker == true || inputs.install-docker == 'true' }}
      with:
        version: version=28.1.1
        
    - name: Install pnpm
      uses: pnpm/action-setup@v4 # pulls version from package.json -> "packageManager"

    - name: Bootstrap app
      shell: bash
      run: |
        pnpm run bootstrap -c
