name: Deploy to EC2 (Development)

on:
  release:
    types:
      [prereleased, released]

env:
  AWS_REGION: us-east-1

jobs:        
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@fdb5b74adc1278ddb777dfed4c988b9d098bb48d # v1.2.1
        with:
          path: app/

      # - name: Send Release Start Notificaton
      #   uses: ./.github/actions/release-notifier
      #   if: always()
      #   with:
      #     environment: Development
      #     version: ${{ steps.extract_version.outputs.version }}
      #     status: started
      #     slack_oauth_token: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}

      - name: "Deploy to Development"
        uses: ./.github/actions/deploy
        with:
          code_deploy_group: ${{ secrets.CODE_DEPLOY_GROUP_NAME_DEV }}
          code_deploy_application: ${{ secrets.CODE_DEPLOY_APPLICATION_NAME }}
          aws_region: ${{ env.AWS_REGION }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          version: ${{ steps.extract_version.outputs.version }}
          s3_bucket: ${{ secrets.QSS_S3_CODE_DEPLOY_BUCKET }}

      # - name: Send Release Start Notificaton
      #   uses: ./.github/actions/release-notifier
      #   if: always()
      #   with:
      #     environment: Development
      #     version: ${{ steps.extract_version.outputs.version }}
      #     status: ${{ job.status }}
      #     slack_oauth_token: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}