name: Deploy to EC2

on:
  release:
    types:
      [prereleased, released]

env:
  AWS_REGION: us-east-1


jobs:        
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - run: |
        commit_id=`git rev-parse HEAD`
        aws deploy create-deployment \
        --application-name ${{ secrets.CODE_DEPLOY_APPLICATION_NAME }} \
        --deployment-group-name ${{ secrets.CODE_DEPLOY_GROUP_NAME }} \
        --github-location repository=TryQuiet/quiet-storage-service,commitId=$commit_id \
        --ignore-application-stop-failures