name: Deploy to EC2 (Development)

on:
  release:
    types:
      [prereleased, released]

env:
  AWS_REGION: us-east-1

jobs:        
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@fdb5b74adc1278ddb777dfed4c988b9d098bb48d # v1.2.1
      - name: Send Release Start Notificaton
        uses: ./.github/actions/release-notifier
        if: always()
        with:
          environment: Development
          version: ${{ steps.extract_version.outputs.version }}
          status: started
          slack_oauth_token: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}
      - name: "Deploy to Development"
        uses: ./.github/actions/deploy
        with:
          code_deploy_group: ${{ secrets.CODE_DEPLOY_GROUP_NAME_DEV }}
          code_deploy_application: ${{ secrets.CODE_DEPLOY_APPLICATION_NAME }}
          aws_region: ${{ env.AWS_REGION }}
      - name: Send Release Start Notificaton
        uses: ./.github/actions/release-notifier
        if: always()
        with:
          environment: Development
          version: ${{ steps.extract_version.outputs.version }}
          status: ${{ job.status }}
          slack_oauth_token: ${{ secrets.SLACK_BOT_OAUTH_TOKEN }}