name: E2E Tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Run E2E tests"
        shell: bash
        run: pnpm run test:e2e:ci
