name: E2E Tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: 'recursive' 

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          install-docker: true

      - name: "Run E2E tests"
        shell: bash
        run: pnpm run run:app test:e2e:ci
