name: Unit Tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: 'recursive' 

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          install-docker: true

      - name: "Prepare test environment"
        shell: bash
        run: pnpm run run:app spinup:tests:ci

      - name: "Run unit tests"
        shell: bash
        run: pnpm run run:app test:ci

      - name: "Teardown test environment"
        if: always()
        shell: bash
        run: pnpm run run:app spindown:tests
